spring:
  application:
    name: sb-spring-boot-intro
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      
server:
  port: 9999